---

- name: Install Python PIP and setuptools
  yum:
    name:
      - python3-pip
      - python3-setuptools
    state: present

- name: Add gpg key
  ansible.builtin.rpm_key:
    key: "https://download.docker.com/linux/centos/gpg"
    state: present

- name: Add repository into repo.d list
  ansible.builtin.yum_repository:
    name: docker
    description: docker repository
    baseurl: "https://download.docker.com/linux/centos/$releasever/$basearch/stable"
    enabled: true
    gpgcheck: true
    gpgkey: "https://download.docker.com/linux/centos/gpg"

- name: Install Docker
  ansible.builtin.yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: true

- name: Start & Enable Docker
  ansible.builtin.service:
    name: "docker"
    enabled: true
    state: started

- name: Install Docker Module for Python
  pip:
    name: docker