Vagrant.configure("2") do |config|

    config.vm.define "wordpress" do |wordpress|
        wordpress.vm.box="generic/ubuntu2004"
        wordpress.vm.hostname = "wordpress"
        wordpress.vm.network "private_network", ip: "192.168.111.201"
        wordpress.vm.provision "shell", path: "provisioning-script.sh"
        wordpress.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
      end
    end

    config.vm.define "wp2" do |wp2|
        wp2.vm.box="generic/ubuntu2004"
        wp2.vm.hostname = "wp2"
        wp2.vm.network "private_network", ip: "192.168.111.202"
        wp2.vm.provision "shell", path: "provisioning-script.sh"
        wp2.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
      end
    end

end