---
# httpd.yml
#
# Service enable action is not a handler. That way
# we can easily stop the service and perform an upgrade
#
### TODO: specify the exact HTTPD version to be installed
- name: Install Apache(latest)
  ansible.builtin.dnf:
    name: httpd
    state: latest
  notify:
    - Start and enable HTTPD