---
# mysql.yml
#
# Additional to MySQL server installation we 
# install the required Python MySQL Connector
# so we can apply CRUD on MySQL DBs
#

- name: Install MySQL(MariaDB) server and client packages
  ansible.builtin.dnf:
    name: "{{ mysql_packages }}"
    state: latest
  notify:
    - Start and enable MySQL

# Manage(CRUD) MySQL DBs with ansible
- name: Install Python MySQL connector
  ansible.builtin.pip:
    name: PyMySQL