---
# service-configs.yml

- name: Configure HTTPD server
  block:
    - name: Increase memory limit for PHP-CLI
      ansible.builtin.lineinfile:
        path: "{{ php_cli_ini_file }}"
        regexp: '^memory_limit'
        line: "{{ php_memory_limit }}"

    - name: Allow port 80
      ansible.posix.firewalld:
        port: 80/tcp
        permanent: yes
        immediate: yes
        state: enabled

    - name: Deploy HTTPD custom config
      ansible.builtin.template:
        src: "{{ httpd_custom_vhost_template }}"
        dest: "{{ httpd_custom_vhost_include }}"
        mode: 0644
  notify:
    - Restart apache