- name: Start and enable HTTPD
  ansible.builtin.service: 
    name: httpd
    enabled: yes
    state: started

- name: Start and enable MySQL
  ansible.builtin.service:
    name: mariadb
    enabled: yes
    state: started

- name: Restart apache
  ansible.builtin.service:
    name: httpd
    state: restarted