---

- name: Create Docker bridge network
  docker_network:
    name: "{{net}}"

- name: Deploy MariaDB
  docker_container:
    image: mariadb
    name: mariadb
    network_mode: "{{net}}"
    volumes:
      - "{{db_volume}}:/var/lib/mysql"
    env:
      MYSQL_ROOT_PASSWORD: somerootpassword
      WORDPRESS_DB_PASSWORD: somemysqlpassword
      WORDPRESS_DB_NAME: db
      WORDPRESS_DB_USER: mysqluser

- name: Deploy WordPress app
  docker_container:
    image: wordpress
    name: wordpress
    restart_policy: always
    network_mode: "{{net}}"
    ports:
      - "80:80"
    links:
      - "{{db_volume}}:/var/lib/mysql"
    volumes:
      - "{{wordpress}}:/var/www/html"
    env:
      WORDPRESS_DB_PASSWORD: somemysqlpassword
      WORDPRESS_DB_NAME: db
      WORDPRESS_DB_USER: mysqluser
      WORDPRESS_DB_HOST: mariadb