Vagrant.configure("2") do |config|

    config.vm.define "wpdocker" do |wpdocker|
        wpdocker.vm.box="generic/ubuntu2004"
        wpdocker.vm.hostname = "wpdocker"
        wpdocker.vm.network "private_network", ip: "192.168.111.201"
        wpdocker.vm.provision "shell", path: "provisioning-script.sh"
        wpdocker.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "2048"]
      end
    end

end