---
node_exporter_version: v1.6.0
node_exporter_image: "prom/node-exporter"
node_exporter_volumes:
  - /proc:/host/proc:ro
  - /sys:/host/sys:ro
  - /:/rootfs:ro
node_exporter_command: >
  --path.procfs=/host/proc
  --path.rootfs=/rootfs
  --path.sysfs=/host/sys
  --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)


cadvisor_version: v0.47.0
cadvisor_image: gcr.io/cadvisor/cadvisor
cadvisor_volumes:
  - /:/rootfs:ro
  - /var/run:/var/run:ro
  - /sys:/sys:ro
  - /var/lib/docker/:/var/lib/docker:ro
  - /dev/disk/:/dev/disk:ro