---
# magentoapp
has_composer: /root/ansible_helpers/installed/composer.txt
has_magento: /root/ansible_helpers/installed/magento.txt
composer_install_script: install_composer.sh
httpd_doc_root: /var/www/html

dbname: mage_db
dbuser: mage_user
dbpass: mage_pass
cent_db_socket: "/var/lib/mysql/mysql.sock"