---
epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm"
remi_repo_url: "https://rpms.remirepo.net/enterprise/remi-release-9.rpm"
remi_app_stream: '@php:remi-8.2'
linux_tools:
  - zip
  - git
php_extensions:
  - php
  - php-cli
  - php-common
  - php-mysql
  - php-pear
  - php-soap
  - php-bcmath
  - php-gd
  - php-intl
  - php-zip