---

- name: Install Python tools(PIP, setuptools, etc)
  yum:
    name: "{{ python_tools }}"
    state: present

- name: Install Python Requests
  ansible.builtin.pip:
    name: "requests<{{ py_requests_version }}"
    state: present

- name: Add GPG key
  ansible.builtin.rpm_key:
    key: "{{ docker_gpg_key }}"
    state: present

- name: Add Docker repository into repo.d list
  ansible.builtin.yum_repository:
    name: docker
    description: docker repository
    baseurl: "{{ docker_repo_base_url }}"
    enabled: true
    gpgcheck: true
    gpgkey: "{{ docker_gpg_key }}"

- name: Install Docker
  ansible.builtin.yum:
    name: "{{ docker_tools }}"
    state: latest
    update_cache: true

# define as handler in case required
- name: Start & Enable Docker Service
  ansible.builtin.service:
    name: "docker"
    enabled: true
    state: started
