- name: Install Elasticsearch, .deb package
  ansible.builtin.apt:
    deb: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.5.2-amd64.deb
    state: present

- name:  Set Java heap size
  ansible.builtin.template:
    src: jvm.options.j2
    dest: /etc/elasticsearch/jvm.options.d/jvm.options
    owner: root
    group: elasticsearch
    mode: '0644'
  notify:
    - restart elasticsearch

- name: ES config - Set up network host
  ansible.builtin.replace:
    path: "{{es_config}}"
    regexp: '#network.host: 192.168.0.1'
    replace: 'network.host: ["localhost", "{{inventory_hostname}}"]'

- name: ES config - Port
  ansible.builtin.replace:
    path: "{{es_config}}"
    regexp: '#http.port: 9200'
    replace: 'http.port: 9200'


- name: ES config - Cluster name
  ansible.builtin.replace:
    path: "{{es_config}}"
    regexp: '#cluster.name: my-application'
    replace: 'cluster.name: mycluster'

- name: ES config - Node name
  ansible.builtin.replace:
    path: "{{es_config}}"
    regexp: '#node.name: node-1'
    replace: 'node.name: monitoring'

- name: ES config -Disable Security Mode
  ansible.builtin.replace:
    path: "{{es_config}}"
    regexp: 'xpack.security.enabled: true'
    replace: 'xpack.security.enabled: false'

- name: Start and enable Elasticsearch
  ansible.builtin.service:
    state: started
    enabled: yes
    name: elasticsearch