Vagrant.configure("2") do |config|

    config.vm.define "wpubuntu" do |wpubuntu|
        wpubuntu.vm.box="generic/ubuntu2004"
        wpubuntu.vm.hostname = "wpubuntu"
        wpubuntu.vm.network "private_network", ip: "192.168.111.201"
        wpubuntu.vm.provision "shell", path: "provisioning-script.sh"
        wpubuntu.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
      end
    end

    config.vm.define "wpubuntu2" do |wpubuntu2|
        wpubuntu2.vm.box="generic/ubuntu2004"
        wpubuntu2.vm.hostname = "wpubuntu2"
        wpubuntu2.vm.network "private_network", ip: "192.168.111.202"
        wpubuntu2.vm.provision "shell", path: "provisioning-script.sh"
        wpubuntu2.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
      end
    end

    config.vm.define "wpcentos" do |wpcentos|
        wpcentos.vm.box="generic/centos9s"
        wpcentos.vm.hostname = "wpcentos"
        wpcentos.vm.network "private_network", ip: "192.168.111.203"
        wpcentos.vm.provision "shell", path: "provisioning-script.sh"
        wpcentos.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
      end
    end

end