### 
# We configure the Certbot to try renew the cert on every 12 hours
# Nginx reload on 6 hours
# As recommended by Certbot doc
### 

- name: Cron Job - LE renewal attemp on every 12 hours
  ansible.builtin.cron:
    name: "LE SSL renewal attempt"
    hour: "*/12"
    job: "date >> {{on_host_le_renew_log}} && docker run --rm --name certbotrenew -v {{on_host_certbot_data_path}}:/etc/letsencrypt -v {{on_host_certbot_data_www}}:/var/www/certbot  certbot/certbot renew >> {{on_host_le_renew_log}}"
    state: "present"

- name: Cron Job - nginx reload on every 6 hours
  ansible.builtin.cron:
    name: "Nginx reload"
    hour: "*/6"
    job: "docker container exec {{container_name_nginx}} nginx -s reload"
    state: "present"