---
# webtier playbook
# Deploy WordPress:
# Set up database
# Copy and chown files
# Config

- name: Create MySQL Database
  mysql_db:
    name: "{{dbname}}"

- name: Create DB user and grant privileges
  mysql_user:
    name: "{{dbuser}}"
    password: "{{dbpass}}"
    priv: "{{dbname}}.*:ALL"
    state: present

- name: Download and extract files
  unarchive:
    src: "https://wordpress.org/latest.tar.gz"
    remote_src: true
    dest: "{{webpath}}"
    extra_opts: [--strip-components=1]

- name: Set Permissions
  file:
    path: "{{webpath}}"
    state: directory
    recurse: true
    owner: www-data
    group: www-data

- name: Rename config file
  command: mv {{webpath}}/wp-config-sample.php {{webpath}}/wp-config.php
  become: true

- name: Remove index.html
  command: rm -f {{webpath}}/index.html
  become: true

- name: Update WP config
  lineinfile:
        path: "{{webpath}}/wp-config.php"
        regexp: "{{item.regexp}}"
        line: "{{item.line}}"
  with_items:
    - {
        "regexp": "define\\( 'DB_NAME', '(.)+' \\);",
        "line": "define( 'DB_NAME', '{{dbname}}' );",
      }
    - {
        "regexp": "define\\( 'DB_USER', '(.)+' \\);",
        "line": "define( 'DB_USER', '{{dbuser}}' );",
      }
    - {
        "regexp": "define\\( 'DB_PASSWORD', '(.)+' \\);",
        "line": "define( 'DB_PASSWORD', '{{dbpass}}' );",
      }
  notify:
      - restart apache
    
