---
# deploy-elastic.yml

- name: Download Elasticsearch, .deb package
  ansible.builtin.get_url:
    url: "{{ es_deb_url }}"
    dest: "{{ es_deb_dest }}"

- name: Install Elasticsearch, .deb package
  ansible.builtin.apt:
    deb: "{{ es_deb_dest }}"
    state: present
  notify:
    - Start and enable elasticsearch