---
- name: Setup (L)AMP stack and deploy WordPress app
  hosts: wpservers
  become: true

  vars:
    dbname: wpdb
    dbuser: wpdbuser
    dbpass: wpdbpass
    webpath: "/var/www/html"

  ### Install all services
  tasks:
    - name: Refresh apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install Apache
      apt:
        name: "apache2"
        state: present

    - name: Install MySQL(MariaDB)
      apt:
        name: mariadb-server
        state: present

    - name: Install PHP
      apt:
        name: php
        state: present

    - name:  Install PHP-CGI(FPM)
      apt:
        name: php-cgi
        state: present

    - name: Install PHP-CLI
      apt:
        name: php-cli
        state: present

    - name: Install apache2 php module
      apt:
        name: libapache2-mod-php
        state: present

    - name: Install PHP MySQL Client
      apt:
        name: php-mysql
        state: latest

    - name: Install Python MySQL Client
      apt:
        name: python3-mysqldb
        state: latest

    - name: Enable Apache Module - mod_rewrite
      apache2_module:
        state: present
        name: rewrite

  ### Setup database and deploy WP app
    - name: Create MySQL Database
      mysql_db:
        name: "{{dbname}}"

    - name: Create DB user and grant privileges
      mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: "{{dbname}}.*:ALL"
        state: present

    - name: Download and extract files
      unarchive:
        src: "https://wordpress.org/latest.tar.gz"
        remote_src: true
        dest: "{{webpath}}"
        extra_opts: [--strip-components=1]

    - name: Set Permissions
      file:
        path: "{{webpath}}"
        state: directory
        recurse: true
        owner: www-data
        group: www-data

    - name: Rename config file
      command: mv {{webpath}}/wp-config-sample.php {{webpath}}/wp-config.php
      become: true

    - name: Remove index.html
      command: rm -f {{webpath}}/index.html
      become: true

    - name: Update WP config
      lineinfile:
            path: "{{webpath}}/wp-config.php"
            regexp: "{{item.regexp}}"
            line: "{{item.line}}"
      with_items:
        - {
            "regexp": "define\\( 'DB_NAME', '(.)+' \\);",
            "line": "define( 'DB_NAME', '{{dbname}}' );",
          }
        - {
            "regexp": "define\\( 'DB_USER', '(.)+' \\);",
            "line": "define( 'DB_USER', '{{dbuser}}' );",
          }
        - {
            "regexp": "define\\( 'DB_PASSWORD', '(.)+' \\);",
            "line": "define( 'DB_PASSWORD', '{{dbpass}}' );",
          }
      notify:
      - restart apache
    
  handlers:
    - name: restart apache
      ansible.builtin.service:
        name: apache2
        state: restarted