---
epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm"
remi_repo_url: "https://rpms.remirepo.net/enterprise/remi-release-9.rpm"
remi_app_stream: '@php:remi-8.2'
linux_tools:
  - zip
  - git
php_extensions:
  - php
  - php-cli
  - php-common
  - php-mysql
  - php-pear
  - php-soap
  - php-bcmath
  - php-gd
  - php-intl
  - php-zip
mysql_packages:
  - mariadb-server
  - mariadb

# PHP-CLI
php_cli_ini_file: /etc/php.ini
php_memory_limit: "memory_limit = 1024M"

# custom httpd vHost
httpd_custom_vhost_template: "httpd-mod-conf.j2"
httpd_custom_vhost_name: "httpd-mod.conf"
httpd_custom_vhost_include: "/etc/httpd/conf.d/{{ httpd_custom_vhost_name }}"