- name: Deploy WordPress app
  docker_container:
    image: wordpress
    name: wordpress
    restart_policy: always
    network_mode: "{{net}}"
    ports:
      - "80:80"
    links:
      - "{{db_volume}}:/var/lib/mysql"
    volumes:
      - "{{wpfs_vol}}:/var/www/html"
    env:
      WORDPRESS_DB_PASSWORD: "{{MARIADB_PASSWORD}}"
      WORDPRESS_DB_NAME: "{{MARIADB_DATABASE}}"
      WORDPRESS_DB_USER: "{{MARIADB_USER}}"
      WORDPRESS_DB_HOST: mariadb