---
- name: Deploy MariaDB
  docker_container:
    image: mariadb
    name: mariadb
    network_mode: "{{net}}"
    volumes:
      - "{{db_volume}}:/var/lib/mysql"
    env:
      MARIADB_ROOT_PASSWORD: "{{MARIADB_ROOT_PASSWORD}}"
      MARIADB_DATABASE: "{{MARIADB_DATABASE}}"
      MARIADB_USER: "{{MARIADB_USER}}"
      MARIADB_PASSWORD: "{{MARIADB_PASSWORD}}"