Vagrant.configure("2") do |config|

    config.vm.define "containers" do |containers|
        containers.vm.box="generic/ubuntu2004"
        containers.vm.hostname = "containers"
        containers.vm.network "private_network", ip: "192.168.111.201"
        containers.vm.provision "shell", path: "provisioning-script.sh"
        containers.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1500"]
      end
    end

    config.vm.define "monitoring" do |monitoring|
        monitoring.vm.box="generic/ubuntu2004"
        monitoring.vm.hostname = "monitoring"
        monitoring.vm.network "private_network", ip: "192.168.111.202"
        monitoring.vm.provision "shell", path: "provisioning-script.sh"
        monitoring.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1500"]
      end
    end

    config.vm.define "staging" do |staging|
        staging.vm.box="generic/ubuntu2004"
        staging.vm.hostname = "staging"
        staging.vm.network "private_network", ip: "192.168.111.203"
        staging.vm.provision "shell", path: "provisioning-script.sh"
        staging.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1500"]
      end
    end


end



# centos9s