- name: Deploy Nginx as Reverse proxy
  docker_container:
    image: nginx
    name: "{{container_name_nginx}}"
    network_mode: "{{docker_wp_net}}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "{{on_host_nginx_config_file}}:{{on_docker_nginx_conf_file}}"
      - "{{on_host_certbot_data_www}}:{{on_docker_nginx_le_path_www}}"
    mounts:
      - source: "{{on_host_certbot_data_path}}"
        target: "{{on_docker_nginx_le_path}}"
        read_only: yes
        type: bind