---
# magento.yml
#
# Clone the Magento repo only if the doc root is empty.
# Then composer install only if $has_magento file does not exist.
# TODO: The magento now install Bash contains many variables,
# it is more convenient to make it a template, upload to the server and execute there.
#

- name: List contents of directory
  ansible.builtin.command: ls "{{ web_doc_root }}"
  register: www_contents

- name: Clone and install Magento project with all dependencies
  community.general.composer:
    command: create-project
    arguments: "--repository-url=https://{{adobe_user}}:{{adobe_pass}}@repo.magento.com  magento/project-community-edition {{ web_doc_root }}"
    working_dir: "{{ web_doc_root }}"
  environment:
    COMPOSER_ALLOW_SUPERUSER: 1
    # prefer_dist: true
  when: www_contents.stdout == ""

- name: Install Magento application.
  ansible.builtin.script: "{{ magento_install_script_name }} 
    {{ inventory_hostname }} 
    {{ groups.elasticserver[0] }} 
    {{ web_doc_root }} 
    {{ elasticsearch_port }} 
    {{ dbname }} 
    {{ dbuser }} 
    {{ dbpass }} 
    {{ mage_admin_user }} 
    {{ mage_admin_pass }} 
    {{ ansible_helper_dir_installed }} 
    {{ flag_file_magento }}"
  args:
    creates: "{{ has_magento }}"
