---
- name: Install Metricbeat
  ansible.builtin.apt:
    deb: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-8.5.2-amd64.deb

### TODO: this should be iterated, check loops
- name: Metricbeat config  -Disable the ES output, enable Logstash output 1
  ansible.builtin.replace:
    path: "{{metricbeat_config}}"
    regexp: 'output.elasticsearch:'
    replace: '#output.elasticsearch:'

- name: Metricbeat config  -Disable the ES output, enable Logstash output 2
  ansible.builtin.replace:
    path: "{{metricbeat_config}}"
    regexp: 'hosts: \["localhost:9200"\]'
    replace: '#hosts: ["localhost:9200"]'

- name: Metricbeat config  -Disable the ES output, enable Logstash output 3
  ansible.builtin.replace:
    path: "{{metricbeat_config}}"
    regexp: '#output.logstash:'
    replace: 'output.logstash:'

- name: Metricbeat config  -Disable the ES output, enable Logstash output 4
  ansible.builtin.replace:
    path: "{{metricbeat_config}}"
    regexp: '#hosts: \["localhost:5044"\]'
    replace: 'hosts: ["{{monitoring_master}}:5044"]'

- name: Start and enable Metricbeat service
  ansible.builtin.service:
    state: started
    enabled: yes
    name: metricbeat