---
- name: permit traffic in default zone for https service
  ansible.posix.firewalld:
    service: https
    permanent: yes
    state: enabled

- name: permit traffic in default zone on port 80/tcp
  ansible.posix.firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled

- name: permit traffic in default zone on port 8080/tcp
  ansible.posix.firewalld:
    port: 8080/tcp
    permanent: yes
    state: enabled