- name: Start and enable elasticsearch
  service:
    name: elasticsearch
    enabled: yes
    state: started
    
- name: Restart elasticsearch
  service:
    name: elasticsearch
    state: restarted
